openapi: '3.0.0'
info:
  title: Person API
  version: '1.0'
  
paths:
  /composers:
    get:
      tags:
        - Persons
      description: Reads,retrieves all persons within database
      summary: Returns a list of composers.     
      operationId: findAllPersons
      responses:
        '200':
          description: A list of persons
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception

    post:
      tags:
        - Persons
      description: Adds a new person object to database
      summary: Create a person composer.
      operationId: createComposer
      requestBody:
        description: Composer object information.
        content:
          application/json:
            schema:
              type: string
              required:
                - firstName
                - lastName
                - roles
                - dependents
                - birthDate
              properties:
                firstName:
                  description: first name of composer
                  type: string
                lastName:
                  description: last name of composer
                  type: string
                  roles:
                   description: Roles
                   type: array
 *                 items:
 *                   type: object
 *                   properties:
 *                     text:
 *                       type: string
 *               dependents:
 *                 description: array of dependantSchema
 *                 type: array
 *                 items:
 *                   type: object
 *                   properties:
 *                     firstName:
 *                       type: string
 *                     lastName:
 *                       type: string
 *               birthDate:
 *                 description: Birthdate of person
 *                 type: string
      
      responses:
        '200':
          description: Created new composer Object
        '500':
          description: Server Exception
        '501':
          description: MongoDB Exception